/* empty css                      */import{i as c,a as g,S as p}from"./assets/vendor-Bs22_3np.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&d(l)}).observe(document,{childList:!0,subtree:!0});function a(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function d(t){if(t.ep)return;t.ep=!0;const n=a(t);fetch(t.href,n)}})();const h=document.getElementById("search-form"),y=document.getElementById("gallery"),L=document.getElementById("loader"),I=document.querySelector(".load-more-container"),s=document.getElementById("load-more"),i=document.getElementById("end-message"),b="46312866-230437729350338e2d6e4b6e5",E="https://pixabay.com/api/",m=40;let r={currentPage:1,currentQuery:"",totalHits:0};function P(){s.textContent="Load more",s.style.display="none",I.appendChild(s),i.style.display="none"}h.addEventListener("submit",S);function S(e){e.preventDefault();const o=document.getElementById("search-query").value.trim();o?(w(o),f(o,r.currentPage)):c.error({title:"Error",message:"Please enter a search term!"})}function w(e){r.currentPage=1,r.currentQuery=e,r.totalHits=0,y.innerHTML="",s.style.display="none",i.style.display="none"}async function f(e,o){u(!0);try{const a=await g.get(E,{params:{key:b,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:m}});B(a.data)}catch{c.error({title:"Error",message:"Something went wrong. Please try again!"})}finally{u(!1)}}function B(e){r.totalHits=e.totalHits,e.hits.length>0?(v(e.hits),x(e.hits.length),R()):c.error({title:"No Results",message:"Sorry, no images found. Please try again!"})}function v(e){const o=e.map(M).join("");y.innerHTML+=o,H()}function M(e){return`
    <a href="${e.largeImageURL}" class="gallery-item">
      <img src="${e.webformatURL}" alt="${e.tags}" />
      <div class="image-info">
        <span><i class="fas fa-heart"></i> ${e.likes}</span>
        <span><i class="fas fa-eye"></i> ${e.views}</span>
        <span><i class="fas fa-comments"></i> ${e.comments}</span>
        <span><i class="fas fa-download"></i> ${e.downloads}</span>
      </div>
    </a>
  `}function H(){new p(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function u(e){L.style.display=e?"block":"none"}function x(e){r.currentPage*m>=r.totalHits?(s.style.display="none",i.style.display="block"):(s.style.display="block",i.style.display="none")}function R(){const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}s.addEventListener("click",$);async function $(){r.currentPage++,await f(r.currentQuery,r.currentPage)}P();
//# sourceMappingURL=index.js.map
